### ISSUE TITLE
Code stopping and not continuing at ENV calls.

### ISSUE THREAD

**Issue by EisbarGFX** [arduino-libraries/Arduino_MKRENV#8]
Using the example code given at the bottom of https://www.arduino.cc/en/Guide/MKRENVShield, and the best wiring I could find given the horriffic insturctions there, any call to ENV (such as if (!ENV.begin()) {}) the Serial output freezes, and it seems that the code does as well. 
Using the Mega 2560 board, my wiring from Mkr Env to board is 14TX to 1TX, 13RX to 0RX, 12SCL to 21SCL, 11SDA to 20SDA, 10Miso to 50, 9SCK to 52, 8MOSI to 51, 7 to 22, 6 to 23, and A2 to A2. 5V and GRD are plugged in correctly.

**Comment by per1234** [comment]
We're providing support for this issue on @EisbarGFX's forum post:
https://forum.arduino.cc/index.php?topic=656961
So I'm going to close this. If we should later determine that there is a related bug or improvement for the library, I'll be happy to reopen this.
