### ISSUE TITLE
Wrong illuminance calculation factor

### ISSUE THREAD

**Issue by ghost** [arduino-libraries/Arduino_MKRENV#9]
The illuminance calculation is done using the factor 2 mV/lx. This results in a current factor of 0.2 uA/lx due to the series resistor of 10k.

According to the datasheet of the TEMT6000 (Rev. 1.9, 23-Aug-11) an illumination of 100 lx results in a current of 50 uA. However, using the factor 0.2 uA/lx multiplied by 100 lx gives a current of 20 uA. Additionally Figure 3 in the datasheet (Photo Current vs. Illuminance) shows a linear relationship with 0.5 uA/lx and not 0.2 uA/lx.

I am aware that the information provided in the datasheet refers to VCE=5V, however this should not lead to such a big difference.

**Comment by agdl** [comment]
@thohohl looking at this apllication note http://www.vishay.com/docs/84154/appnotesensors.pdf page 4

you can see that supplying from 3 to 5V with 10kOhm load we can measure from 1lux to 1000lux (2mV to 2V) so in our case we can arrive till 1650lux at 3.3V using the whole AD range

Is it ok now?

**Comment by ghost** [comment]
@agdl the calculation used in the application note you provided refers to sensor TEMT6200FX01 and according the schematic MKRENVShieldV4.0_sch.pdf, type TEMT6000X01 is mounted.

**Comment by per1234** [comment]
Thanks so much for reporting this @thohohl!

I believe https://github.com/arduino-libraries/Arduino_MKRENV/commit/70eeaced535a26fae01cffbdea856f61da827cdf changes the calculation to use the 0.5 ua/lx spec you mentioned. If you check it out and find it's still not as you expect, feel free to comment here and we'll investigate.
